name: Meerkat-II-layer
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
    - name: Verifing source code with Artificial Intelligence.
      run: showcase.sh
